//[validator-field](../../../index.md)/[com.chrynan.validator](../index.md)/[FieldValidationException](index.md)



# FieldValidationException  
 [common] class [FieldValidationException](index.md) : [RuntimeException](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-runtime-exception/index.html)

A [RuntimeException](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-runtime-exception/index.html) that indicates there was an error asserting that a field was valid or invalid.



This exception is thrown from the [assertValidField](../assert-valid-field.md) and [assertInvalidField](../assert-invalid-field.md) functions.

   


## Properties  
  
|  Name |  Summary | 
|---|---|
| <a name="com.chrynan.validator/FieldValidationException/cause/#/PointingToDeclaration/"></a>[cause](index.md#%5Bcom.chrynan.validator%2FFieldValidationException%2Fcause%2F%23%2FPointingToDeclaration%2F%5D%2FProperties%2F1752467176)| <a name="com.chrynan.validator/FieldValidationException/cause/#/PointingToDeclaration/"></a> [common] open val [cause](index.md#%5Bcom.chrynan.validator%2FFieldValidationException%2Fcause%2F%23%2FPointingToDeclaration%2F%5D%2FProperties%2F1752467176): [Throwable](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html)?   <br>|
| <a name="com.chrynan.validator/FieldValidationException/message/#/PointingToDeclaration/"></a>[message](index.md#%5Bcom.chrynan.validator%2FFieldValidationException%2Fmessage%2F%23%2FPointingToDeclaration%2F%5D%2FProperties%2F1752467176)| <a name="com.chrynan.validator/FieldValidationException/message/#/PointingToDeclaration/"></a> [common] open val [message](index.md#%5Bcom.chrynan.validator%2FFieldValidationException%2Fmessage%2F%23%2FPointingToDeclaration%2F%5D%2FProperties%2F1752467176): [String](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html)?   <br>|

